import type { Setlist, Track } from "./play-types";

export const DEMO_TRACKS: Track[] = [
  {
    id: "k7m2p9",
    displayName: "Sunday Kick Loop",
    filename: "sunday-kick-loop.wav",
    songTitle: "Great Are You Lord",
    originalBpm: 120,
    bpmUnconfirmed: false,
    key: "D",
    keyMode: "major",
    timeSignature: "4/4",
    cached: true,
  },
  {
    id: "n4w8q1",
    displayName: "Shaker Groove",
    filename: "shaker-groove-154.mp3",
    songTitle: "Way Maker",
    originalBpm: 154,
    bpmUnconfirmed: true,
    key: "No Key",
    keyMode: "major",
    timeSignature: "4/4",
    cached: true,
  },
  {
    id: "r2t6h5",
    displayName: "Conga Fill",
    filename: "conga-fill-92.wav",
    songTitle: null,
    originalBpm: 92,
    bpmUnconfirmed: false,
    key: "G",
    keyMode: "minor",
    timeSignature: "6/8",
    cached: false,
  },
  {
    id: "b9c3x7",
    displayName: "Tambourine Pulse",
    filename: "tambourine-168.mp3",
    songTitle: "Build My Life",
    originalBpm: 168,
    bpmUnconfirmed: false,
    key: "E",
    keyMode: "major",
    timeSignature: "4/4",
    cached: true,
  },
  {
    id: "q8k4v3",
    displayName: "Extended Ambient Pad Swell With Reverse Cymbal Tail",
    filename: "extended-ambient-pad-swell-with-reverse-cymbal-tail-72.wav",
    songTitle: "Holy Forever (Combined Service Extended Arrangement)",
    originalBpm: 72,
    bpmUnconfirmed: false,
    key: "Bb",
    keyMode: "major",
    timeSignature: "4/4",
    cached: true,
  },
  {
    id: "z6y2n5",
    displayName: "Full Band Percussion Stack With Djembe, Shaker And Rim Clicks",
    filename: "full-band-percussion-stack-djembe-shaker-rim-clicks-104.mp3",
    songTitle: null,
    originalBpm: 104,
    bpmUnconfirmed: true,
    key: "F#",
    keyMode: "minor",
    timeSignature: "12/8",
    cached: false,
  },
  {
    id: "h5n8d2",
    displayName: "Cajon Backbeat",
    filename: "cajon-backbeat-88.wav",
    songTitle: "What A Beautiful Name",
    originalBpm: 88,
    bpmUnconfirmed: false,
    key: "A",
    keyMode: "major",
    timeSignature: "3/4",
    cached: true,
  },
  {
    id: "v4l7g6",
    displayName: "Half Time Kit",
    filename: "half-time-kit-76.mp3",
    songTitle: "Goodness Of God",
    originalBpm: 76,
    bpmUnconfirmed: false,
    key: "Ab",
    keyMode: "major",
    timeSignature: "4/4",
    cached: true,
  },
  {
    id: "j2s9r4",
    displayName: "Click Only Guide",
    filename: "click-only-guide-140.wav",
    songTitle: null,
    originalBpm: 140,
    bpmUnconfirmed: false,
    key: "No Key",
    keyMode: "major",
    timeSignature: "2/4",
    cached: false,
  },
  {
    id: "t8b3f1",
    displayName: "Stomp Clap Intro",
    filename: "stomp-clap-intro-132.mp3",
    songTitle: "This Is Amazing Grace",
    originalBpm: 132,
    bpmUnconfirmed: true,
    key: "B",
    keyMode: "major",
    timeSignature: "4/4",
    cached: true,
  },
  {
    id: "m6z1c9",
    displayName: "Brush Kit Swell",
    filename: "brush-kit-swell-64.wav",
    songTitle: "It Is Well With My Soul",
    originalBpm: 64,
    bpmUnconfirmed: false,
    key: "C",
    keyMode: "minor",
    timeSignature: "6/8",
    cached: false,
  },
  {
    id: "a1p4k8",
    displayName: "Soft Piano Click",
    filename: "soft-piano-click-68.wav",
    songTitle: "Be Still My Soul",
    originalBpm: 68,
    bpmUnconfirmed: false,
    key: "D",
    keyMode: "major",
    timeSignature: "4/4",
    cached: true,
  },
  {
    id: "f3w7e2",
    displayName: "Slow Build Tom",
    filename: "slow-build-tom-74.mp3",
    songTitle: null,
    originalBpm: 74,
    bpmUnconfirmed: true,
    key: "G",
    keyMode: "minor",
    timeSignature: "4/4",
    cached: false,
  },
  {
    id: "d8r5n1",
    displayName: "Lounge Brush Pattern",
    filename: "lounge-brush-pattern-78.wav",
    songTitle: "In Christ Alone",
    originalBpm: 78,
    bpmUnconfirmed: false,
    key: "E",
    keyMode: "major",
    timeSignature: "3/4",
    cached: true,
  },
  {
    id: "u2h6m9",
    displayName: "Acoustic Strum Loop",
    filename: "acoustic-strum-loop-82.mp3",
    songTitle: "10,000 Reasons",
    originalBpm: 82,
    bpmUnconfirmed: false,
    key: "A",
    keyMode: "major",
    timeSignature: "4/4",
    cached: true,
  },
  {
    id: "y5t1b4",
    displayName: "Conga Layer",
    filename: "conga-layer-86.wav",
    songTitle: null,
    originalBpm: 86,
    bpmUnconfirmed: false,
    key: "F",
    keyMode: "minor",
    timeSignature: "6/8",
    cached: false,
  },
  {
    id: "i9c7l3",
    displayName: "Worship Groove A",
    filename: "worship-groove-a-94.mp3",
    songTitle: "Reckless Love",
    originalBpm: 94,
    bpmUnconfirmed: false,
    key: "Bb",
    keyMode: "major",
    timeSignature: "4/4",
    cached: true,
  },
  {
    id: "o4x8s6",
    displayName: "Mid Tempo Shaker",
    filename: "mid-tempo-shaker-98.wav",
    songTitle: "Oceans",
    originalBpm: 98,
    bpmUnconfirmed: true,
    key: "D",
    keyMode: "minor",
    timeSignature: "4/4",
    cached: false,
  },
  {
    id: "e6k2v7",
    displayName: "Steady Kick Pattern",
    filename: "steady-kick-pattern-108.mp3",
    songTitle: "Living Hope",
    originalBpm: 108,
    bpmUnconfirmed: false,
    key: "C",
    keyMode: "major",
    timeSignature: "4/4",
    cached: true,
  },
  {
    id: "w1n5j8",
    displayName: "Synth Pulse Loop",
    filename: "synth-pulse-loop-112.wav",
    songTitle: null,
    originalBpm: 112,
    bpmUnconfirmed: false,
    key: "Ab",
    keyMode: "major",
    timeSignature: "4/4",
    cached: true,
  },
  {
    id: "l7g3p2",
    displayName: "Gospel Backbeat",
    filename: "gospel-backbeat-116.mp3",
    songTitle: "Every Praise",
    originalBpm: 116,
    bpmUnconfirmed: false,
    key: "Eb",
    keyMode: "major",
    timeSignature: "4/4",
    cached: false,
  },
  {
    id: "x9f4d1",
    displayName: "Uplift Groove",
    filename: "uplift-groove-124.wav",
    songTitle: "Good Good Father",
    originalBpm: 124,
    bpmUnconfirmed: false,
    key: "G",
    keyMode: "major",
    timeSignature: "4/4",
    cached: true,
  },
  {
    id: "c5m8r6",
    displayName: "Driving Hi-Hat",
    filename: "driving-hi-hat-128.mp3",
    songTitle: null,
    originalBpm: 128,
    bpmUnconfirmed: true,
    key: "No Key",
    keyMode: "major",
    timeSignature: "4/4",
    cached: false,
  },
  {
    id: "p2b7h9",
    displayName: "Anthemic Build",
    filename: "anthemic-build-136.wav",
    songTitle: "Raise A Hallelujah",
    originalBpm: 136,
    bpmUnconfirmed: false,
    key: "B",
    keyMode: "major",
    timeSignature: "4/4",
    cached: true,
  },
  {
    id: "n8v1t5",
    displayName: "Energetic Clap Loop",
    filename: "energetic-clap-loop-142.mp3",
    songTitle: "Graves Into Gardens",
    originalBpm: 142,
    bpmUnconfirmed: false,
    key: "D",
    keyMode: "major",
    timeSignature: "4/4",
    cached: true,
  },
  {
    id: "k3y6w4",
    displayName: "Fast Shaker Drive",
    filename: "fast-shaker-drive-148.wav",
    songTitle: null,
    originalBpm: 148,
    bpmUnconfirmed: false,
    key: "A",
    keyMode: "minor",
    timeSignature: "4/4",
    cached: false,
  },
  {
    id: "r7s2q8",
    displayName: "Upbeat Conga Stack",
    filename: "upbeat-conga-stack-156.mp3",
    songTitle: "Tremble",
    originalBpm: 156,
    bpmUnconfirmed: true,
    key: "F#",
    keyMode: "minor",
    timeSignature: "4/4",
    cached: true,
  },
  {
    id: "b4d9f3",
    displayName: "Double Kick Pulse",
    filename: "double-kick-pulse-162.wav",
    songTitle: null,
    originalBpm: 162,
    bpmUnconfirmed: false,
    key: "E",
    keyMode: "major",
    timeSignature: "4/4",
    cached: false,
  },
  {
    id: "h1m6c7",
    displayName: "Breakbeat Loop",
    filename: "breakbeat-loop-170.mp3",
    songTitle: "Surrounded",
    originalBpm: 170,
    bpmUnconfirmed: false,
    key: "C",
    keyMode: "minor",
    timeSignature: "4/4",
    cached: true,
  },
  {
    id: "v8j4n2",
    displayName: "High Energy Perc",
    filename: "high-energy-perc-178.wav",
    songTitle: null,
    originalBpm: 178,
    bpmUnconfirmed: false,
    key: "G",
    keyMode: "major",
    timeSignature: "2/4",
    cached: false,
  },
];

export const DEMO_SETLISTS: Setlist[] = [
  {
    id: "x3f8s2",
    name: "Sunday AM",
    cached: true,
    slots: [
      {
        trackId: "k7m2p9",
        slotLabel: "Track 1",
        targetBpm: 120,
        timeSignature: "4/4",
        key: "D",
        keyMode: "major",
      },
      {
        trackId: "n4w8q1",
        slotLabel: "Track 2",
        targetBpm: 154,
        timeSignature: "4/4",
        key: "No Key",
        keyMode: "major",
      },
      {
        trackId: "b9c3x7",
        slotLabel: "Track 3",
        targetBpm: 166,
        timeSignature: "4/4",
        key: "E",
        keyMode: "major",
      },
    ],
  },
  {
    id: "p5d1m8",
    name: "Rehearsal Wed",
    cached: false,
    slots: [
      {
        trackId: "r2t6h5",
        slotLabel: "Track 1",
        targetBpm: 92,
        timeSignature: "6/8",
        key: "G",
        keyMode: "minor",
      },
      {
        trackId: "k7m2p9",
        slotLabel: "Track 2",
        targetBpm: 118,
        timeSignature: "4/4",
        key: "C",
        keyMode: "major",
      },
    ],
  },
  {
    id: "w7j9t4",
    name: "Sunday Morning Combined Service With Youth Band And Choir",
    cached: false,
    slots: [
      {
        trackId: "q8k4v3",
        slotLabel: "Opening Worship Set, Track 1",
        targetBpm: 72,
        timeSignature: "4/4",
        key: "Bb",
        keyMode: "major",
      },
      {
        trackId: "z6y2n5",
        slotLabel: "Communion Response And Offering, Track 2",
        targetBpm: 104,
        timeSignature: "12/8",
        key: "F#",
        keyMode: "minor",
      },
      {
        trackId: "k7m2p9",
        slotLabel: "Track 3",
        targetBpm: 120,
        timeSignature: "4/4",
        key: "D",
        keyMode: "major",
      },
    ],
  },
  {
    id: "g4r7y1",
    name: "Youth Night",
    cached: true,
    slots: [
      {
        trackId: "t8b3f1",
        slotLabel: "Track 1",
        targetBpm: 138,
        timeSignature: "4/4",
        key: "B",
        keyMode: "major",
      },
      {
        trackId: "j2s9r4",
        slotLabel: "Track 2",
        targetBpm: 140,
        timeSignature: "2/4",
        key: "No Key",
        keyMode: "major",
      },
      {
        trackId: "b9c3x7",
        slotLabel: "Track 3",
        targetBpm: 168,
        timeSignature: "4/4",
        key: "E",
        keyMode: "major",
      },
      {
        trackId: "h5n8d2",
        slotLabel: "Track 4",
        targetBpm: 88,
        timeSignature: "3/4",
        key: "A",
        keyMode: "major",
      },
    ],
  },
  {
    id: "c2v6b8",
    name: "Prayer Night Acoustic",
    cached: true,
    slots: [
      {
        trackId: "m6z1c9",
        slotLabel: "Track 1",
        targetBpm: 64,
        timeSignature: "6/8",
        key: "C",
        keyMode: "minor",
      },
      {
        trackId: "v4l7g6",
        slotLabel: "Track 2",
        targetBpm: 80,
        timeSignature: "4/4",
        key: "G",
        keyMode: "major",
      },
    ],
  },
  {
    id: "s9h3k6",
    name: "Carols By Candlelight",
    cached: false,
    slots: [
      {
        trackId: "h5n8d2",
        slotLabel: "Processional, Track 1",
        targetBpm: 84,
        timeSignature: "3/4",
        key: "A",
        keyMode: "major",
      },
      {
        trackId: "q8k4v3",
        slotLabel: "Reading Underscore, Track 2",
        targetBpm: 70,
        timeSignature: "4/4",
        key: "Bb",
        keyMode: "major",
      },
      {
        trackId: "v4l7g6",
        slotLabel: "Track 3",
        targetBpm: 76,
        timeSignature: "4/4",
        key: "Ab",
        keyMode: "major",
      },
      {
        trackId: "t8b3f1",
        slotLabel: "Closing, Track 4",
        targetBpm: 132,
        timeSignature: "4/4",
        key: "B",
        keyMode: "major",
      },
    ],
  },
  {
    id: "a7n2p5",
    name: "Easter Sunday",
    cached: true,
    slots: [
      {
        trackId: "x9f4d1",
        slotLabel: "Track 1",
        targetBpm: 124,
        timeSignature: "4/4",
        key: "G",
        keyMode: "major",
      },
      {
        trackId: "p2b7h9",
        slotLabel: "Track 2",
        targetBpm: 136,
        timeSignature: "4/4",
        key: "B",
        keyMode: "major",
      },
      {
        trackId: "h1m6c7",
        slotLabel: "Track 3",
        targetBpm: 170,
        timeSignature: "4/4",
        key: "C",
        keyMode: "minor",
      },
    ],
  },
  {
    id: "f1k8r3",
    name: "Midweek Prayer",
    cached: true,
    slots: [
      {
        trackId: "a1p4k8",
        slotLabel: "Track 1",
        targetBpm: 68,
        timeSignature: "4/4",
        key: "D",
        keyMode: "major",
      },
      {
        trackId: "d8r5n1",
        slotLabel: "Track 2",
        targetBpm: 78,
        timeSignature: "3/4",
        key: "E",
        keyMode: "major",
      },
      {
        trackId: "u2h6m9",
        slotLabel: "Track 3",
        targetBpm: 82,
        timeSignature: "4/4",
        key: "A",
        keyMode: "major",
      },
    ],
  },
  {
    id: "l6v9b2",
    name: "Band Rehearsal Run-Through",
    cached: false,
    slots: [
      {
        trackId: "e6k2v7",
        slotLabel: "Track 1",
        targetBpm: 108,
        timeSignature: "4/4",
        key: "C",
        keyMode: "major",
      },
      {
        trackId: "l7g3p2",
        slotLabel: "Track 2",
        targetBpm: 116,
        timeSignature: "4/4",
        key: "Eb",
        keyMode: "major",
      },
      {
        trackId: "c5m8r6",
        slotLabel: "Track 3",
        targetBpm: 128,
        timeSignature: "4/4",
        key: "No Key",
        keyMode: "major",
      },
      {
        trackId: "n8v1t5",
        slotLabel: "Track 4",
        targetBpm: 142,
        timeSignature: "4/4",
        key: "D",
        keyMode: "major",
      },
    ],
  },
  {
    id: "t3w7h1",
    name: "Christmas Eve",
    cached: true,
    slots: [
      {
        trackId: "f3w7e2",
        slotLabel: "Prelude, Track 1",
        targetBpm: 74,
        timeSignature: "4/4",
        key: "G",
        keyMode: "minor",
      },
      {
        trackId: "m6z1c9",
        slotLabel: "Track 2",
        targetBpm: 64,
        timeSignature: "6/8",
        key: "C",
        keyMode: "minor",
      },
      {
        trackId: "v4l7g6",
        slotLabel: "Track 3",
        targetBpm: 76,
        timeSignature: "4/4",
        key: "Ab",
        keyMode: "major",
      },
    ],
  },
  {
    id: "m5c8j4",
    name: "Summer Outdoor Service",
    cached: false,
    slots: [
      {
        trackId: "i9c7l3",
        slotLabel: "Track 1",
        targetBpm: 94,
        timeSignature: "4/4",
        key: "Bb",
        keyMode: "major",
      },
      {
        trackId: "o4x8s6",
        slotLabel: "Track 2",
        targetBpm: 98,
        timeSignature: "4/4",
        key: "D",
        keyMode: "minor",
      },
      {
        trackId: "w1n5j8",
        slotLabel: "Track 3",
        targetBpm: 112,
        timeSignature: "4/4",
        key: "Ab",
        keyMode: "major",
      },
    ],
  },
  {
    id: "d2p6y9",
    name: "Conference Saturday Night",
    cached: true,
    slots: [
      {
        trackId: "r7s2q8",
        slotLabel: "Opener, Track 1",
        targetBpm: 156,
        timeSignature: "4/4",
        key: "F#",
        keyMode: "minor",
      },
      {
        trackId: "b4d9f3",
        slotLabel: "Track 2",
        targetBpm: 162,
        timeSignature: "4/4",
        key: "E",
        keyMode: "major",
      },
      {
        trackId: "v8j4n2",
        slotLabel: "Closer, Track 3",
        targetBpm: 178,
        timeSignature: "2/4",
        key: "G",
        keyMode: "major",
      },
    ],
  },
  {
    id: "q1h5n7",
    name: "Acoustic Sunday PM",
    cached: true,
    slots: [
      {
        trackId: "y5t1b4",
        slotLabel: "Track 1",
        targetBpm: 86,
        timeSignature: "6/8",
        key: "F",
        keyMode: "minor",
      },
      {
        trackId: "h5n8d2",
        slotLabel: "Track 2",
        targetBpm: 88,
        timeSignature: "3/4",
        key: "A",
        keyMode: "major",
      },
      {
        trackId: "r2t6h5",
        slotLabel: "Track 3",
        targetBpm: 92,
        timeSignature: "6/8",
        key: "G",
        keyMode: "minor",
      },
    ],
  },
  {
    id: "z8f3k6",
    name: "New Year Celebration",
    cached: false,
    slots: [
      {
        trackId: "k3y6w4",
        slotLabel: "Track 1",
        targetBpm: 148,
        timeSignature: "4/4",
        key: "A",
        keyMode: "minor",
      },
      {
        trackId: "n4w8q1",
        slotLabel: "Track 2",
        targetBpm: 154,
        timeSignature: "4/4",
        key: "No Key",
        keyMode: "major",
      },
      {
        trackId: "b9c3x7",
        slotLabel: "Track 3",
        targetBpm: 168,
        timeSignature: "4/4",
        key: "E",
        keyMode: "major",
      },
      {
        trackId: "j2s9r4",
        slotLabel: "Track 4",
        targetBpm: 140,
        timeSignature: "2/4",
        key: "No Key",
        keyMode: "major",
      },
    ],
  },
  {
    id: "e4r1t8",
    name: "Kids Ministry Sunday",
    cached: true,
    slots: [
      {
        trackId: "c5m8r6",
        slotLabel: "Track 1",
        targetBpm: 128,
        timeSignature: "4/4",
        key: "No Key",
        keyMode: "major",
      },
      {
        trackId: "t8b3f1",
        slotLabel: "Track 2",
        targetBpm: 132,
        timeSignature: "4/4",
        key: "B",
        keyMode: "major",
      },
      {
        trackId: "k7m2p9",
        slotLabel: "Track 3",
        targetBpm: 120,
        timeSignature: "4/4",
        key: "D",
        keyMode: "major",
      },
    ],
  },
  {
    id: "n6b2w5",
    name: "Baptism Service",
    cached: false,
    slots: [
      {
        trackId: "q8k4v3",
        slotLabel: "Underscore, Track 1",
        targetBpm: 72,
        timeSignature: "4/4",
        key: "Bb",
        keyMode: "major",
      },
      {
        trackId: "x9f4d1",
        slotLabel: "Track 2",
        targetBpm: 124,
        timeSignature: "4/4",
        key: "G",
        keyMode: "major",
      },
      {
        trackId: "z6y2n5",
        slotLabel: "Track 3",
        targetBpm: 104,
        timeSignature: "12/8",
        key: "F#",
        keyMode: "minor",
      },
    ],
  },
];

export function getTrackById(id: string): Track | undefined {
  return DEMO_TRACKS.find((track) => track.id === id);
}

export function getSetlistById(id: string): Setlist | undefined {
  return DEMO_SETLISTS.find((setlist) => setlist.id === id);
}

export function getTrackForSlot(setlist: Setlist, slotIndex: number): Track | undefined {
  const slot = setlist.slots[slotIndex];
  if (!slot) {
    return undefined;
  }
  return getTrackById(slot.trackId);
}
