import type { Setlist, Track } from "./play-types";

export const DEMO_TRACKS: Track[] = [
  {
    id: "k7m2p9",
    displayName: "Sunday Kick Loop",
    filename: "sunday-kick-loop.wav",
    songTitle: "Great Are You Lord",
    originalBpm: 120,
    bpmUnconfirmed: false,
    key: "D",
    keyMode: "major",
    timeSignature: "4/4",
    cached: true,
  },
  {
    id: "n4w8q1",
    displayName: "Shaker Groove",
    filename: "shaker-groove-154.mp3",
    songTitle: "Way Maker",
    originalBpm: 154,
    bpmUnconfirmed: true,
    key: "No Key",
    keyMode: "major",
    timeSignature: "4/4",
    cached: true,
  },
  {
    id: "r2t6h5",
    displayName: "Conga Fill",
    filename: "conga-fill-92.wav",
    songTitle: null,
    originalBpm: 92,
    bpmUnconfirmed: false,
    key: "G",
    keyMode: "minor",
    timeSignature: "6/8",
    cached: false,
  },
  {
    id: "b9c3x7",
    displayName: "Tambourine Pulse",
    filename: "tambourine-168.mp3",
    songTitle: "Build My Life",
    originalBpm: 168,
    bpmUnconfirmed: false,
    key: "E",
    keyMode: "major",
    timeSignature: "4/4",
    cached: true,
  },
  {
    id: "q8k4v3",
    displayName: "Extended Ambient Pad Swell With Reverse Cymbal Tail",
    filename: "extended-ambient-pad-swell-with-reverse-cymbal-tail-72.wav",
    songTitle: "Holy Forever (Combined Service Extended Arrangement)",
    originalBpm: 72,
    bpmUnconfirmed: false,
    key: "Bb",
    keyMode: "major",
    timeSignature: "4/4",
    cached: true,
  },
  {
    id: "z6y2n5",
    displayName: "Full Band Percussion Stack With Djembe, Shaker And Rim Clicks",
    filename: "full-band-percussion-stack-djembe-shaker-rim-clicks-104.mp3",
    songTitle: null,
    originalBpm: 104,
    bpmUnconfirmed: true,
    key: "F#",
    keyMode: "minor",
    timeSignature: "12/8",
    cached: false,
  },
  {
    id: "h5n8d2",
    displayName: "Cajon Backbeat",
    filename: "cajon-backbeat-88.wav",
    songTitle: "What A Beautiful Name",
    originalBpm: 88,
    bpmUnconfirmed: false,
    key: "A",
    keyMode: "major",
    timeSignature: "3/4",
    cached: true,
  },
  {
    id: "v4l7g6",
    displayName: "Half Time Kit",
    filename: "half-time-kit-76.mp3",
    songTitle: "Goodness Of God",
    originalBpm: 76,
    bpmUnconfirmed: false,
    key: "Ab",
    keyMode: "major",
    timeSignature: "4/4",
    cached: true,
  },
  {
    id: "j2s9r4",
    displayName: "Click Only Guide",
    filename: "click-only-guide-140.wav",
    songTitle: null,
    originalBpm: 140,
    bpmUnconfirmed: false,
    key: "No Key",
    keyMode: "major",
    timeSignature: "2/4",
    cached: false,
  },
  {
    id: "t8b3f1",
    displayName: "Stomp Clap Intro",
    filename: "stomp-clap-intro-132.mp3",
    songTitle: "This Is Amazing Grace",
    originalBpm: 132,
    bpmUnconfirmed: true,
    key: "B",
    keyMode: "major",
    timeSignature: "4/4",
    cached: true,
  },
  {
    id: "m6z1c9",
    displayName: "Brush Kit Swell",
    filename: "brush-kit-swell-64.wav",
    songTitle: "It Is Well With My Soul",
    originalBpm: 64,
    bpmUnconfirmed: false,
    key: "C",
    keyMode: "minor",
    timeSignature: "6/8",
    cached: false,
  },
];

export const DEMO_SETLISTS: Setlist[] = [
  {
    id: "x3f8s2",
    name: "Sunday AM",
    cached: true,
    slots: [
      {
        trackId: "k7m2p9",
        slotLabel: "Track 1",
        targetBpm: 120,
        timeSignature: "4/4",
        key: "D",
        keyMode: "major",
      },
      {
        trackId: "n4w8q1",
        slotLabel: "Track 2",
        targetBpm: 154,
        timeSignature: "4/4",
        key: "No Key",
        keyMode: "major",
      },
      {
        trackId: "b9c3x7",
        slotLabel: "Track 3",
        targetBpm: 166,
        timeSignature: "4/4",
        key: "E",
        keyMode: "major",
      },
    ],
  },
  {
    id: "p5d1m8",
    name: "Rehearsal Wed",
    cached: false,
    slots: [
      {
        trackId: "r2t6h5",
        slotLabel: "Track 1",
        targetBpm: 92,
        timeSignature: "6/8",
        key: "G",
        keyMode: "minor",
      },
      {
        trackId: "k7m2p9",
        slotLabel: "Track 2",
        targetBpm: 118,
        timeSignature: "4/4",
        key: "C",
        keyMode: "major",
      },
    ],
  },
  {
    id: "w7j9t4",
    name: "Sunday Morning Combined Service With Youth Band And Choir",
    cached: false,
    slots: [
      {
        trackId: "q8k4v3",
        slotLabel: "Opening Worship Set, Track 1",
        targetBpm: 72,
        timeSignature: "4/4",
        key: "Bb",
        keyMode: "major",
      },
      {
        trackId: "z6y2n5",
        slotLabel: "Communion Response And Offering, Track 2",
        targetBpm: 104,
        timeSignature: "12/8",
        key: "F#",
        keyMode: "minor",
      },
      {
        trackId: "k7m2p9",
        slotLabel: "Track 3",
        targetBpm: 120,
        timeSignature: "4/4",
        key: "D",
        keyMode: "major",
      },
    ],
  },
  {
    id: "g4r7y1",
    name: "Youth Night",
    cached: true,
    slots: [
      {
        trackId: "t8b3f1",
        slotLabel: "Track 1",
        targetBpm: 138,
        timeSignature: "4/4",
        key: "B",
        keyMode: "major",
      },
      {
        trackId: "j2s9r4",
        slotLabel: "Track 2",
        targetBpm: 140,
        timeSignature: "2/4",
        key: "No Key",
        keyMode: "major",
      },
      {
        trackId: "b9c3x7",
        slotLabel: "Track 3",
        targetBpm: 168,
        timeSignature: "4/4",
        key: "E",
        keyMode: "major",
      },
      {
        trackId: "h5n8d2",
        slotLabel: "Track 4",
        targetBpm: 88,
        timeSignature: "3/4",
        key: "A",
        keyMode: "major",
      },
    ],
  },
  {
    id: "c2v6b8",
    name: "Prayer Night Acoustic",
    cached: true,
    slots: [
      {
        trackId: "m6z1c9",
        slotLabel: "Track 1",
        targetBpm: 64,
        timeSignature: "6/8",
        key: "C",
        keyMode: "minor",
      },
      {
        trackId: "v4l7g6",
        slotLabel: "Track 2",
        targetBpm: 80,
        timeSignature: "4/4",
        key: "G",
        keyMode: "major",
      },
    ],
  },
  {
    id: "s9h3k6",
    name: "Carols By Candlelight",
    cached: false,
    slots: [
      {
        trackId: "h5n8d2",
        slotLabel: "Processional, Track 1",
        targetBpm: 84,
        timeSignature: "3/4",
        key: "A",
        keyMode: "major",
      },
      {
        trackId: "q8k4v3",
        slotLabel: "Reading Underscore, Track 2",
        targetBpm: 70,
        timeSignature: "4/4",
        key: "Bb",
        keyMode: "major",
      },
      {
        trackId: "v4l7g6",
        slotLabel: "Track 3",
        targetBpm: 76,
        timeSignature: "4/4",
        key: "Ab",
        keyMode: "major",
      },
      {
        trackId: "t8b3f1",
        slotLabel: "Closing, Track 4",
        targetBpm: 132,
        timeSignature: "4/4",
        key: "B",
        keyMode: "major",
      },
    ],
  },
];

export function getTrackById(id: string): Track | undefined {
  return DEMO_TRACKS.find((track) => track.id === id);
}

export function getSetlistById(id: string): Setlist | undefined {
  return DEMO_SETLISTS.find((setlist) => setlist.id === id);
}

export function getTrackForSlot(setlist: Setlist, slotIndex: number): Track | undefined {
  const slot = setlist.slots[slotIndex];
  if (!slot) {
    return undefined;
  }
  return getTrackById(slot.trackId);
}
